/**
 * UNIVERSAL MODELS CONFIG
 * Auto-generated by scripts/update_universal_models.py
 * Source of truth: src.ai.models
 */

export const models = [
  {
    "name": "GLM 4.7 1T MoE Cerebras",
    "slug": "glm-4-7-1t-moe-cerebras",
    "size": 1000.0,
    "provider": "Cerebras"
  },
  {
    "name": "Mistral Large 3 675B Instruct Nvidia",
    "slug": "mistral-large-3-675b-instruct-nvidia",
    "size": 675.0,
    "provider": "Nvidia"
  },
  {
    "name": "Mistral Large 3 675B Instruct Mistral",
    "slug": "mistral-large-3-675b-instruct-mistral",
    "size": 675.0,
    "provider": "Mistral"
  },
  {
    "name": "DeepSeek R1T2 Chimera OpenRouter",
    "slug": "deepseek-r1t2-chimera-openrouter",
    "size": 671.0,
    "provider": "Openrouter"
  },
  {
    "name": "DeepSeek V3.2 Nvidia",
    "slug": "deepseek-v3-2-nvidia",
    "size": 671.0,
    "provider": "Nvidia"
  },
  {
    "name": "Qwen3 Coder 480B MoE OpenRouter",
    "slug": "qwen3-coder-480b-moe-openrouter",
    "size": 480.0,
    "provider": "Openrouter"
  },
  {
    "name": "R1T Chimera OpenRouter",
    "slug": "r1t-chimera-openrouter",
    "size": 450.0,
    "provider": "Openrouter"
  },
  {
    "name": "Llama 3.1 405B Instruct GitHub",
    "slug": "llama-3-1-405b-instruct-github",
    "size": 405.0,
    "provider": "Github"
  },
  {
    "name": "MiMo V2 Flash 309B MoE OpenRouter",
    "slug": "mimo-v2-flash-309b-moe-openrouter",
    "size": 309.0,
    "provider": "Openrouter"
  },
  {
    "name": "Devstral 2 123B Instruct OpenRouter",
    "slug": "devstral-2-123b-instruct-openrouter",
    "size": 123.0,
    "provider": "Openrouter"
  },
  {
    "name": "Devstral 2 123B Mistral",
    "slug": "devstral-2-123b-mistral",
    "size": 123.0,
    "provider": "Mistral"
  },
  {
    "name": "Llama 3.2 90B Vision Instruct Groq",
    "slug": "llama-3-2-90b-vision-instruct-groq",
    "size": 90.0,
    "provider": "Groq"
  },
  {
    "name": "Mixtral 8x7B Instruct Groq",
    "slug": "mixtral-8x7b-instruct-groq",
    "size": 56.0,
    "provider": "Groq"
  },
  {
    "name": "Qwen QwQ 32B Groq",
    "slug": "qwen-qwq-32b-groq",
    "size": 32.0,
    "provider": "Groq"
  },
  {
    "name": "Qwen3 32B Instruct Cerebras",
    "slug": "qwen3-32b-instruct-cerebras",
    "size": 32.0,
    "provider": "Cerebras"
  },
  {
    "name": "Gemma 3 27B Instruct Gemini",
    "slug": "gemma-3-27b-instruct-gemini",
    "size": 27.0,
    "provider": "Gemini"
  },
  {
    "name": "GPT OSS 20B Cerebras",
    "slug": "gpt-oss-20b-cerebras",
    "size": 20.0,
    "provider": "Cerebras"
  },
  {
    "name": "GLM 4.5 Air OpenRouter",
    "slug": "glm-4-5-air-openrouter",
    "size": 20.0,
    "provider": "Openrouter"
  }
];
