#!/usr/bin/env python3
"""
Update Universal Models Config
Generates universal/config/models.js with the latest list of sidebar-enabled models.
"""

import json
import sys
from pathlib import Path

# Setup paths
SCRIPT_DIR = Path(__file__).parent.absolute()
ROOT_DIR = SCRIPT_DIR.parent
sys.path.append(str(ROOT_DIR))

from src.ai.models.helpers import get_sidebar_models_for_html

def main():
    print("Generating universal/config/models.js...")

    try:
        models = get_sidebar_models_for_html()

        js_content = f"""/**
 * UNIVERSAL MODELS CONFIG
 * Auto-generated by scripts/update_universal_models.py
 * Source of truth: src.ai.models
 */

export const models = {json.dumps(models, indent=2)};
"""

        config_path = ROOT_DIR / "universal" / "config" / "models.js"
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(js_content, encoding="utf-8")

        print(f"✅ Successfully wrote {len(models)} models to {config_path}")

    except Exception as e:
        print(f"❌ Failed to generate models config: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
